services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: 'mysql:5.7.17'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=demoproto
#      - MYSQL_DATABASE=gomall
    volumes:
      - E:/DockerData/mysql:/var/lib/mysql  # 将宿主机 E 盘的路径挂载到容器中的 /var/lib/mysql 保留运行数据
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #字符集设置

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222

