// Code generated by Kitex v0.9.1. DO NOT EDIT.

package checkoutservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	checkout "gomall/rpc_gen/kitex_gen/checkout"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CheckOut": kitex.NewMethodInfo(
		checkOutHandler,
		newCheckOutArgs,
		newCheckOutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	checkOutServiceServiceInfo                = NewServiceInfo()
	checkOutServiceServiceInfoForClient       = NewServiceInfoForClient()
	checkOutServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return checkOutServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return checkOutServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return checkOutServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CheckOutService"
	handlerType := (*checkout.CheckOutService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "checkout",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func checkOutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(checkout.CheckOutReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(checkout.CheckOutService).CheckOut(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckOutArgs:
		success, err := handler.(checkout.CheckOutService).CheckOut(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckOutResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckOutArgs() interface{} {
	return &CheckOutArgs{}
}

func newCheckOutResult() interface{} {
	return &CheckOutResult{}
}

type CheckOutArgs struct {
	Req *checkout.CheckOutReq
}

func (p *CheckOutArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(checkout.CheckOutReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CheckOutArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CheckOutArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CheckOutArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckOutArgs) Unmarshal(in []byte) error {
	msg := new(checkout.CheckOutReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckOutArgs_Req_DEFAULT *checkout.CheckOutReq

func (p *CheckOutArgs) GetReq() *checkout.CheckOutReq {
	if !p.IsSetReq() {
		return CheckOutArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckOutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckOutArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckOutResult struct {
	Success *checkout.CheckOutResp
}

var CheckOutResult_Success_DEFAULT *checkout.CheckOutResp

func (p *CheckOutResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(checkout.CheckOutResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CheckOutResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CheckOutResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CheckOutResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckOutResult) Unmarshal(in []byte) error {
	msg := new(checkout.CheckOutResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckOutResult) GetSuccess() *checkout.CheckOutResp {
	if !p.IsSetSuccess() {
		return CheckOutResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckOutResult) SetSuccess(x interface{}) {
	p.Success = x.(*checkout.CheckOutResp)
}

func (p *CheckOutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckOutResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CheckOut(ctx context.Context, Req *checkout.CheckOutReq) (r *checkout.CheckOutResp, err error) {
	var _args CheckOutArgs
	_args.Req = Req
	var _result CheckOutResult
	if err = p.c.Call(ctx, "CheckOut", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
